# Generated by Django 3.1 on 2020-08-27 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phonenumber',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Temail',
            new_name='teacher_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Tname',
            new_name='teacher_name',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
